version: '3.8'

services:
  postgres_service:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: book_inventory
    networks:
      - app_network

  streamlit_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8501"  # Changed port mapping
    networks:
      - app_network

networks:
  app_network:
    driver: bridge